services:
  backend:
    build:
      context: ./backend
      args:
        SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    env_file:
      - .env.dev
