version: "3.8"
services:
  backend:
    build:
      context: ./backend
      args:
        SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    env_file:
      - .env.prod
