version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: sonexa-postgres
    environment:
      POSTGRES_DB: sonexa_ai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sonexa-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sonexa-backend
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sonexa_ai
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID:-your-google-client-id}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET:-your-google-client-secret}
      CORS_ALLOWED_ORIGINS: http://localhost:3000
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - sonexa-network
    volumes:
      - ./logs:/app/logs

volumes:
  postgres_data:

networks:
  sonexa-network:
    driver: bridge
